@id = 67799cbe9624433994e69780

### GET request to the server
GET http://localhost:3000/recipes

### GET request to the server

GET http://localhost:3000/recipes/{{id}}

### POST request to the server
POST http://localhost:3000/recipes
Content-Type: application/json

{
  "name": "Kanapka z awokado",
  "ingredients": [
    "2 kromki chleba pełnoziarnistego",
    "1 dojrzałe awokado",
    "1 łyżeczka soku z cytryny",
    "szczypta soli",
    "szczypta pieprzu",
    "opcjonalnie: plasterki pomidora lub jajko na twardo"
  ],
  "description": "Obierz awokado, rozgnieć widelcem i wymieszaj z sokiem z cytryny, solą i pieprzem. Posmaruj pastą kromki chleba. Opcjonalnie dodaj plasterki pomidora lub jajko na twardo.",
  "opinion": 4
}

### PUT request to the server
PUT http://localhost:3000/recipes/{{id}}
Content-Type: application/json

{
  "name": "Smoothie bananowo-truskawkowe",
  "ingredients": [
    "1 banan",
    "200 g truskawek (świeżych lub mrożonych)",
    "200 ml mleka (lub napoju roślinnego)",
    "1 łyżeczka miodu (opcjonalnie)"
  ],
  "description": "Obierz banana i umyj truskawki. Wszystkie składniki zmiksuj w blenderze na gładką konsystencję. Podawaj od razu, najlepiej schłodzone.",
  "opinion": 5
}

### DELETE request to the server
DELETE http://localhost:3000/recipes/{{id}}